import type { NextPage } from "next";
import { useEffect } from "react";
import Head from "next/head";
import Script from "next/script";

// local
import { Navbar, Accordion, AnimatedBg } from "../components";
import Accordions from "../templates/Home/Accordions";
import Intro from "../templates/Home/Intro";

const Home: NextPage = () => {
	useEffect(() => {
		const threeScript = document.createElement("script");
		threeScript.setAttribute("id", "threeScript");
		threeScript.setAttribute("src", "https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js");
		document.getElementsByTagName("head")[0].appendChild(threeScript);
		return () => {
			if (threeScript) {
				threeScript.remove();
			}
		};
	}, []);

	return (
		<div className="w-full text-center bg-indigo-900 text-white">
			<Head>
				<title>Frontierx</title>
				<meta name="description" content="Frontierx - Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<AnimatedBg>
				<main className="m-auto max-w-screen-2xl">
					<Intro />
					<Accordions />
				</main>
			</AnimatedBg>
			<footer className="py-20 w-full bg-[#0D0D0D]">
				<p className="m-auto  ">LOGO</p>
			</footer>
		</div>
	);
};

export default Home;
